site_name: Abby's Notes
site_url: https://aNon1mo4-21.github.io

theme:
  name: material
  language: zh  # 设置中文界面
  palette: 
    primary: indigo # 主题色
    accent: indigo
  features:
    - navigation.expand  # 默认展开左侧菜单
    - search.suggest
    - search.highlight
    - content.code.copy   # 代码块右上角显示复制按钮

nav:
  - Welcome: index.md