site_name: Abby's Notes
site_url: https://aNon1mo4-21.github.io

theme:
  name: material
  language: en  # 设置中文界面
  palette: 
    primary: indigo # 主题色
    accent: indigo
  features:
    - navigation.tabs # 顶部导航栏
    - search.suggest
    - search.highlight
    - navigation.expand  # 默认展开左侧菜单
    - content.code.copy   # 代码块右上角显示复制按钮
    - navigation.indexes
    - content.tabs.link
markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
nav:
  - Home: index.md
  - 📐 Mathematics:
      - Overview: math/index.md
      - Mathematical Analysis: math/analysis.md
      - Linear Algebra: math/linear-algebra.md
      - Probability & Statistics: math/probability.md
      - Differential Equations: math/ode.md
  - 💻 Programming:
      - Overview: coding/index.md
      - C/C++ Development: coding/cpp.md
      - Python Scripting: coding/python.md
      - Hardware Design (Verilog): coding/verilog.md
  - 🔬 Research:
      - Exploration: research/exploration.md  # 留待后续细分讨论
  - 🛠️ Toolkit:
      - Software & Tools: toolkit/software.md
      - Site Maintenance: toolkit/mkdocs-guide.md # 维护当前网站的操作
  - About: about.md